Lucia work
enake/helix-poc pull request #39
Opened 2023-07-06 10:59 UTC by Tiseanu

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--<repo>--<owner>.hlx.page/
- After: https://<branch>--<repo>--<owner>.hlx.page/

2023-07-06 12:56 UTC, enake approved these changes

2023-07-06 16:02 UTC, vladalexandruradulescu commented on blocks/c-device-protection-box/c-device-protection-box.css
> +    width: 136%;
why 136% ? and not 138 ? this is to specific ... maybe adjust it to a normal value

2023-07-06 16:03 UTC, vladalexandruradulescu commented on blocks/c-dropdownbox/c-dropdownbox.css
> +  .c-dropdownbox-container .block .bottomText {
. bottomText => .bottom-text

2023-07-06 16:04 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn/c-productswithvpn.css
> +    width: 74%;
74% ... to specific, reduce it to 60% or a human readable value

2023-07-06 16:05 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn/c-productswithvpn.css
> +    width: 610px;
above you are using % value for the width ( 74%, here 610px, maybe use uniform values everywhere ? )

2023-07-06 16:05 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn/c-productswithvpn.css
> +        width: 92%;
92% to specific, use 60 / 70 / 80 / 90

2023-07-06 16:06 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn/c-productswithvpn.css
> +        width: 97%;
same here

2023-07-06 16:06 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn/c-productswithvpn.js
> +      /*
remove unused code

2023-07-06 16:08 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn2/c-productswithvpn2.css
> +        padding: 3%;
padding: 3% => use px value

2023-07-06 16:08 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn2/c-productswithvpn2.css
> +        width: 94%;
94%

2023-07-06 16:08 UTC, vladalexandruradulescu commented on blocks/c-productswithvpn2/c-productswithvpn2.css
> +        padding: 3%;
3%

2023-07-06 16:12 UTC, vladalexandruradulescu commented on scripts/scripts.js
> +        const checkboxClass = e.target.classList[0];
remove unused code

2023-07-06 16:13 UTC, vladalexandruradulescu commented on styles/styles.css
> +  .py-5 {
we shouldn't override bootstrap classes

2023-07-07 07:42 UTC, vladalexandruradulescu requested changes

2023-07-07 07:42 UTC, vladalexandruradulescu commented on blocks/c-device-protection-box/c-device-protection-box.css
> +    width: 120%;
we must fix this container issues and the one from above

2023-07-07 09:10 UTC, merged