Add fragment block
enake/helix-poc pull request #83
Opened 2023-08-18 16:23 UTC by Matei-Iordache

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/test
- After: https://fragment-block--helix-poc--enake.hlx.page/consumer/en/test

2023-08-21 11:04 UTC, Tiseanu approved these changes

2023-08-22 10:46 UTC, vladalexandruradulescu requested changes

2023-08-22 10:46 UTC, vladalexandruradulescu commented on blocks/fragment/fragment.js
> +async function loadFragment(path) {
let's add a e2e test for this one

2023-08-30 12:47 UTC, Matei-Iordache reviewed
This has been discussed and is no longer needed

2023-08-30 12:48 UTC, Matei-Iordache reviewed
sas

2023-08-30 12:58 UTC, Matei-Iordache reviewed
lgtm

2023-08-30 12:59 UTC, Matei-Iordache commented on blocks/fragment/fragment.js
> +async function loadFragment(path) {
solved

2023-08-30 15:29 UTC, merged