DEX-14472 | Style and logic changes for new LP on b-banner and c-icon…
enake/helix-poc pull request #93
Opened 2023-08-29 08:55 UTC by Matei-Iordache

…-box-grid

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--helix-poc--enake.hlx.page/consumer/en/renew/avfree-ts-opt
- After: https://DEX-14472--new-LP--helix-poc--enake.hlx.page/consumer/en/renew/avfree-ts-opt

2023-08-31 08:54 UTC, vladalexandruradulescu commented on blocks/b-banner/b-banner.css
> +  background: url("../../images/icons/check_full.png") 0 3px no-repeat transparent;
we should use svgs

2023-08-31 08:55 UTC, vladalexandruradulescu commented on blocks/b-banner/b-banner.scss
> +      height: 721px;
this height value is ultra specific, usually this is not the case, maybe use a more general value like: 700px, 750px, 100%

2023-08-31 13:31 UTC, Matei-Iordache commented on blocks/b-banner/b-banner.css
> +  background: url("../../images/icons/check_full.png") 0 3px no-repeat transparent;
Added the svg variant of this png

2023-09-01 11:57 UTC, Tiseanu approved these changes

2023-09-01 11:57 UTC, Tiseanu approved these changes

2023-09-01 12:15 UTC, vladalexandruradulescu requested changes

2023-09-01 12:15 UTC, vladalexandruradulescu commented on blocks/b-banner/b-banner.css
>    display: none;
this will still download the image under the hood, have a look on b-single-quote.js

2023-09-01 12:15 UTC, vladalexandruradulescu commented on blocks/b-banner/b-banner.scss
>        display: none;
same issue as above, we shouldn't render the image it self from the first time

2023-09-04 08:45 UTC, vladalexandruradulescu approved these changes

2023-09-04 10:02 UTC, merged